# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: paxos.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='paxos.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0bpaxos.proto\x1a\x1bgoogle/protobuf/empty.proto\"\"\n\x04\x44\x61ta\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\"\x1f\n\x0bPrepareArgs\x12\x10\n\x08proposal\x18\x01 \x01(\x03\"_\n\x0cPrepareReply\x12\x17\n\x0fprepareProposal\x18\x01 \x01(\x03\x12\x18\n\x10\x61\x63\x63\x65ptedProposal\x18\x02 \x01(\x03\x12\x1c\n\racceptedValue\x18\x03 \x01(\x0b\x32\x05.Data\"4\n\nAcceptArgs\x12\x10\n\x08proposal\x18\x01 \x01(\x03\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Data\"\x1f\n\x0b\x41\x63\x63\x65ptReply\x12\x10\n\x08\x61\x63\x63\x65pted\x18\x01 \x01(\x08\"4\n\nDecideArgs\x12\x10\n\x08proposal\x18\x01 \x01(\x03\x12\x14\n\x05value\x18\x02 \x01(\x0b\x32\x05.Data\"\x1e\n\x0b\x44\x65\x63ideReply\x12\x0f\n\x07\x64\x65\x63ided\x18\x01 \x01(\x08\")\n\x02Op\x12\n\n\x02op\x18\x01 \x01(\t\x12\x17\n\x08keyValue\x18\x02 \x01(\x0b\x32\x05.Data\".\n\tStartArgs\x12\x10\n\x08proposal\x18\x01 \x01(\x03\x12\x0f\n\x02op\x18\x02 \x01(\x0b\x32\x03.Op\"\x1e\n\nFinishArgs\x12\x10\n\x08proposal\x18\x01 \x01(\x03\"/\n\x08Response\x12\x12\n\nstatusCode\x18\x01 \x01(\x05\x12\x0f\n\x07message\x18\x02 \x01(\t\"%\n\x07Request\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t2\x8c\x02\n\x05Paxos\x12-\n\x05start\x12\n.StartArgs\x1a\x16.google.protobuf.Empty\"\x00\x12*\n\x07propose\x12\x05.Data\x1a\x16.google.protobuf.Empty\"\x00\x12(\n\x07prepare\x12\x0c.PrepareArgs\x1a\r.PrepareReply\"\x00\x12%\n\x06\x61\x63\x63\x65pt\x12\x0b.AcceptArgs\x1a\x0c.AcceptReply\"\x00\x12&\n\x07\x64\x65\x63ided\x12\x0b.DecideArgs\x1a\x0c.DecideReply\"\x00\x12/\n\x06\x66inish\x12\x0b.FinishArgs\x1a\x16.google.protobuf.Empty\"\x00\x32\x81\x01\n\rKeyValueStore\x12#\n\ngetRequest\x12\x08.Request\x1a\t.Response\"\x00\x12#\n\nputRequest\x12\x08.Request\x1a\t.Response\"\x00\x12&\n\rdeleteRequest\x12\x08.Request\x1a\t.Response\"\x00\x62\x06proto3'
  ,
  dependencies=[google_dot_protobuf_dot_empty__pb2.DESCRIPTOR,])




_DATA = _descriptor.Descriptor(
  name='Data',
  full_name='Data',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Data.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Data.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=44,
  serialized_end=78,
)


_PREPAREARGS = _descriptor.Descriptor(
  name='PrepareArgs',
  full_name='PrepareArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='PrepareArgs.proposal', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=80,
  serialized_end=111,
)


_PREPAREREPLY = _descriptor.Descriptor(
  name='PrepareReply',
  full_name='PrepareReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='prepareProposal', full_name='PrepareReply.prepareProposal', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceptedProposal', full_name='PrepareReply.acceptedProposal', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='acceptedValue', full_name='PrepareReply.acceptedValue', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=113,
  serialized_end=208,
)


_ACCEPTARGS = _descriptor.Descriptor(
  name='AcceptArgs',
  full_name='AcceptArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='AcceptArgs.proposal', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='AcceptArgs.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=262,
)


_ACCEPTREPLY = _descriptor.Descriptor(
  name='AcceptReply',
  full_name='AcceptReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='accepted', full_name='AcceptReply.accepted', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=264,
  serialized_end=295,
)


_DECIDEARGS = _descriptor.Descriptor(
  name='DecideArgs',
  full_name='DecideArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='DecideArgs.proposal', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='DecideArgs.value', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=297,
  serialized_end=349,
)


_DECIDEREPLY = _descriptor.Descriptor(
  name='DecideReply',
  full_name='DecideReply',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='decided', full_name='DecideReply.decided', index=0,
      number=1, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=351,
  serialized_end=381,
)


_OP = _descriptor.Descriptor(
  name='Op',
  full_name='Op',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op', full_name='Op.op', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='keyValue', full_name='Op.keyValue', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=383,
  serialized_end=424,
)


_STARTARGS = _descriptor.Descriptor(
  name='StartArgs',
  full_name='StartArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='StartArgs.proposal', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='op', full_name='StartArgs.op', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=426,
  serialized_end=472,
)


_FINISHARGS = _descriptor.Descriptor(
  name='FinishArgs',
  full_name='FinishArgs',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='proposal', full_name='FinishArgs.proposal', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=474,
  serialized_end=504,
)


_RESPONSE = _descriptor.Descriptor(
  name='Response',
  full_name='Response',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statusCode', full_name='Response.statusCode', index=0,
      number=1, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='message', full_name='Response.message', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=506,
  serialized_end=553,
)


_REQUEST = _descriptor.Descriptor(
  name='Request',
  full_name='Request',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='key', full_name='Request.key', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Request.value', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=555,
  serialized_end=592,
)

_PREPAREREPLY.fields_by_name['acceptedValue'].message_type = _DATA
_ACCEPTARGS.fields_by_name['value'].message_type = _DATA
_DECIDEARGS.fields_by_name['value'].message_type = _DATA
_OP.fields_by_name['keyValue'].message_type = _DATA
_STARTARGS.fields_by_name['op'].message_type = _OP
DESCRIPTOR.message_types_by_name['Data'] = _DATA
DESCRIPTOR.message_types_by_name['PrepareArgs'] = _PREPAREARGS
DESCRIPTOR.message_types_by_name['PrepareReply'] = _PREPAREREPLY
DESCRIPTOR.message_types_by_name['AcceptArgs'] = _ACCEPTARGS
DESCRIPTOR.message_types_by_name['AcceptReply'] = _ACCEPTREPLY
DESCRIPTOR.message_types_by_name['DecideArgs'] = _DECIDEARGS
DESCRIPTOR.message_types_by_name['DecideReply'] = _DECIDEREPLY
DESCRIPTOR.message_types_by_name['Op'] = _OP
DESCRIPTOR.message_types_by_name['StartArgs'] = _STARTARGS
DESCRIPTOR.message_types_by_name['FinishArgs'] = _FINISHARGS
DESCRIPTOR.message_types_by_name['Response'] = _RESPONSE
DESCRIPTOR.message_types_by_name['Request'] = _REQUEST
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Data = _reflection.GeneratedProtocolMessageType('Data', (_message.Message,), {
  'DESCRIPTOR' : _DATA,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:Data)
  })
_sym_db.RegisterMessage(Data)

PrepareArgs = _reflection.GeneratedProtocolMessageType('PrepareArgs', (_message.Message,), {
  'DESCRIPTOR' : _PREPAREARGS,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:PrepareArgs)
  })
_sym_db.RegisterMessage(PrepareArgs)

PrepareReply = _reflection.GeneratedProtocolMessageType('PrepareReply', (_message.Message,), {
  'DESCRIPTOR' : _PREPAREREPLY,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:PrepareReply)
  })
_sym_db.RegisterMessage(PrepareReply)

AcceptArgs = _reflection.GeneratedProtocolMessageType('AcceptArgs', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTARGS,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:AcceptArgs)
  })
_sym_db.RegisterMessage(AcceptArgs)

AcceptReply = _reflection.GeneratedProtocolMessageType('AcceptReply', (_message.Message,), {
  'DESCRIPTOR' : _ACCEPTREPLY,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:AcceptReply)
  })
_sym_db.RegisterMessage(AcceptReply)

DecideArgs = _reflection.GeneratedProtocolMessageType('DecideArgs', (_message.Message,), {
  'DESCRIPTOR' : _DECIDEARGS,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:DecideArgs)
  })
_sym_db.RegisterMessage(DecideArgs)

DecideReply = _reflection.GeneratedProtocolMessageType('DecideReply', (_message.Message,), {
  'DESCRIPTOR' : _DECIDEREPLY,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:DecideReply)
  })
_sym_db.RegisterMessage(DecideReply)

Op = _reflection.GeneratedProtocolMessageType('Op', (_message.Message,), {
  'DESCRIPTOR' : _OP,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:Op)
  })
_sym_db.RegisterMessage(Op)

StartArgs = _reflection.GeneratedProtocolMessageType('StartArgs', (_message.Message,), {
  'DESCRIPTOR' : _STARTARGS,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:StartArgs)
  })
_sym_db.RegisterMessage(StartArgs)

FinishArgs = _reflection.GeneratedProtocolMessageType('FinishArgs', (_message.Message,), {
  'DESCRIPTOR' : _FINISHARGS,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:FinishArgs)
  })
_sym_db.RegisterMessage(FinishArgs)

Response = _reflection.GeneratedProtocolMessageType('Response', (_message.Message,), {
  'DESCRIPTOR' : _RESPONSE,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:Response)
  })
_sym_db.RegisterMessage(Response)

Request = _reflection.GeneratedProtocolMessageType('Request', (_message.Message,), {
  'DESCRIPTOR' : _REQUEST,
  '__module__' : 'paxos_pb2'
  # @@protoc_insertion_point(class_scope:Request)
  })
_sym_db.RegisterMessage(Request)



_PAXOS = _descriptor.ServiceDescriptor(
  name='Paxos',
  full_name='Paxos',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=595,
  serialized_end=863,
  methods=[
  _descriptor.MethodDescriptor(
    name='start',
    full_name='Paxos.start',
    index=0,
    containing_service=None,
    input_type=_STARTARGS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='propose',
    full_name='Paxos.propose',
    index=1,
    containing_service=None,
    input_type=_DATA,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='prepare',
    full_name='Paxos.prepare',
    index=2,
    containing_service=None,
    input_type=_PREPAREARGS,
    output_type=_PREPAREREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='accept',
    full_name='Paxos.accept',
    index=3,
    containing_service=None,
    input_type=_ACCEPTARGS,
    output_type=_ACCEPTREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='decided',
    full_name='Paxos.decided',
    index=4,
    containing_service=None,
    input_type=_DECIDEARGS,
    output_type=_DECIDEREPLY,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='finish',
    full_name='Paxos.finish',
    index=5,
    containing_service=None,
    input_type=_FINISHARGS,
    output_type=google_dot_protobuf_dot_empty__pb2._EMPTY,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_PAXOS)

DESCRIPTOR.services_by_name['Paxos'] = _PAXOS


_KEYVALUESTORE = _descriptor.ServiceDescriptor(
  name='KeyValueStore',
  full_name='KeyValueStore',
  file=DESCRIPTOR,
  index=1,
  serialized_options=None,
  serialized_start=866,
  serialized_end=995,
  methods=[
  _descriptor.MethodDescriptor(
    name='getRequest',
    full_name='KeyValueStore.getRequest',
    index=0,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='putRequest',
    full_name='KeyValueStore.putRequest',
    index=1,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='deleteRequest',
    full_name='KeyValueStore.deleteRequest',
    index=2,
    containing_service=None,
    input_type=_REQUEST,
    output_type=_RESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_KEYVALUESTORE)

DESCRIPTOR.services_by_name['KeyValueStore'] = _KEYVALUESTORE

# @@protoc_insertion_point(module_scope)
