# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

from google.protobuf import empty_pb2 as google_dot_protobuf_dot_empty__pb2
import lib.paxos_pb2 as paxos__pb2


class PaxosStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.start = channel.unary_unary(
                '/Paxos/start',
                request_serializer=paxos__pb2.StartArgs.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.propose = channel.unary_unary(
                '/Paxos/propose',
                request_serializer=paxos__pb2.Data.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )
        self.prepare = channel.unary_unary(
                '/Paxos/prepare',
                request_serializer=paxos__pb2.PrepareArgs.SerializeToString,
                response_deserializer=paxos__pb2.PrepareReply.FromString,
                )
        self.accept = channel.unary_unary(
                '/Paxos/accept',
                request_serializer=paxos__pb2.AcceptArgs.SerializeToString,
                response_deserializer=paxos__pb2.AcceptReply.FromString,
                )
        self.decided = channel.unary_unary(
                '/Paxos/decided',
                request_serializer=paxos__pb2.DecideArgs.SerializeToString,
                response_deserializer=paxos__pb2.DecideReply.FromString,
                )
        self.finish = channel.unary_unary(
                '/Paxos/finish',
                request_serializer=paxos__pb2.FinishArgs.SerializeToString,
                response_deserializer=google_dot_protobuf_dot_empty__pb2.Empty.FromString,
                )


class PaxosServicer(object):
    """Missing associated documentation comment in .proto file"""

    def start(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def propose(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def prepare(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def accept(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def decided(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def finish(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_PaxosServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'start': grpc.unary_unary_rpc_method_handler(
                    servicer.start,
                    request_deserializer=paxos__pb2.StartArgs.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'propose': grpc.unary_unary_rpc_method_handler(
                    servicer.propose,
                    request_deserializer=paxos__pb2.Data.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
            'prepare': grpc.unary_unary_rpc_method_handler(
                    servicer.prepare,
                    request_deserializer=paxos__pb2.PrepareArgs.FromString,
                    response_serializer=paxos__pb2.PrepareReply.SerializeToString,
            ),
            'accept': grpc.unary_unary_rpc_method_handler(
                    servicer.accept,
                    request_deserializer=paxos__pb2.AcceptArgs.FromString,
                    response_serializer=paxos__pb2.AcceptReply.SerializeToString,
            ),
            'decided': grpc.unary_unary_rpc_method_handler(
                    servicer.decided,
                    request_deserializer=paxos__pb2.DecideArgs.FromString,
                    response_serializer=paxos__pb2.DecideReply.SerializeToString,
            ),
            'finish': grpc.unary_unary_rpc_method_handler(
                    servicer.finish,
                    request_deserializer=paxos__pb2.FinishArgs.FromString,
                    response_serializer=google_dot_protobuf_dot_empty__pb2.Empty.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Paxos', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Paxos(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def start(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Paxos/start',
            paxos__pb2.StartArgs.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def propose(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Paxos/propose',
            paxos__pb2.Data.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def prepare(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Paxos/prepare',
            paxos__pb2.PrepareArgs.SerializeToString,
            paxos__pb2.PrepareReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def accept(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Paxos/accept',
            paxos__pb2.AcceptArgs.SerializeToString,
            paxos__pb2.AcceptReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def decided(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Paxos/decided',
            paxos__pb2.DecideArgs.SerializeToString,
            paxos__pb2.DecideReply.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def finish(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Paxos/finish',
            paxos__pb2.FinishArgs.SerializeToString,
            google_dot_protobuf_dot_empty__pb2.Empty.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)


class KeyValueStoreStub(object):
    """Missing associated documentation comment in .proto file"""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.getRequest = channel.unary_unary(
                '/KeyValueStore/getRequest',
                request_serializer=paxos__pb2.Request.SerializeToString,
                response_deserializer=paxos__pb2.Response.FromString,
                )
        self.putRequest = channel.unary_unary(
                '/KeyValueStore/putRequest',
                request_serializer=paxos__pb2.Request.SerializeToString,
                response_deserializer=paxos__pb2.Response.FromString,
                )
        self.deleteRequest = channel.unary_unary(
                '/KeyValueStore/deleteRequest',
                request_serializer=paxos__pb2.Request.SerializeToString,
                response_deserializer=paxos__pb2.Response.FromString,
                )


class KeyValueStoreServicer(object):
    """Missing associated documentation comment in .proto file"""

    def getRequest(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def putRequest(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def deleteRequest(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_KeyValueStoreServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'getRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.getRequest,
                    request_deserializer=paxos__pb2.Request.FromString,
                    response_serializer=paxos__pb2.Response.SerializeToString,
            ),
            'putRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.putRequest,
                    request_deserializer=paxos__pb2.Request.FromString,
                    response_serializer=paxos__pb2.Response.SerializeToString,
            ),
            'deleteRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.deleteRequest,
                    request_deserializer=paxos__pb2.Request.FromString,
                    response_serializer=paxos__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'KeyValueStore', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class KeyValueStore(object):
    """Missing associated documentation comment in .proto file"""

    @staticmethod
    def getRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/getRequest',
            paxos__pb2.Request.SerializeToString,
            paxos__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def putRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/putRequest',
            paxos__pb2.Request.SerializeToString,
            paxos__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def deleteRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/KeyValueStore/deleteRequest',
            paxos__pb2.Request.SerializeToString,
            paxos__pb2.Response.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
